### ISSUE TITLE
When Touch on Mobile browser tree disappear

### ISSUE THREAD

**Issue by Premlimbachiya** [shenoyranjith/family-tree-generator#3]
on mobile browser tree b is disapper

**Comment by shenoyranjith** [comment]
Thanks for the info. Will look into this.

**Comment by shenoyranjith** [comment]
This is now fixed. Could you please upgrade to v0.1.2 and confirm?

**Comment by Premlimbachiya** [comment]
yes touch issue is solve but zoom in zoom out is not working

**Comment by shenoyranjith** [comment]
Zoom is also added for mobile devices.
